### ISSUE TITLE
Missing RequireJS config

### ISSUE THREAD

**Issue by aswanepoel** [webjars/typeaheadjs#10]
Using Play framework.
org.webjars.RequireJS.getSetupJavaScript does not generate requirejs.config entry 

The following message appears in the log file:
[warn] 2016-03-03 09:57:09,266 o.w.RequireJS - Could not read WebJar RequireJS config for: typeaheadjs 0.10.4
Please file a bug at: http://github.com/webjars/typeaheadjs/issues/new

**Comment by jamesward** [comment]
This was fixed by #5 so you'll need to use a newer version like `0.10.4-2`.
